### ISSUE TITLE
[BitSail][Connector] Support local file source connector

### ISSUE THREAD

**Issue by garyli1019** [bytedance/bitsail#112]
## Is your feature request related to a problem? Please describe

We need to read local file as source. CSV file format could be a good start.

## Describe the solution you'd like

Use V1 source connector interface, read CSV file as source and able to write to `PrintSink`

**Comment by Jake-00** [comment]
Hi, there! I'm interested in adding this feature for BitSail, could you assign me this issue?

**Comment by garyli1019** [comment]
@Jake-00 assigned to you!

**Comment by Jake-00** [comment]
Hi Gary@garyli1019, I had two questions below:
1. Dose local CSV reader better implement _SimpleSourceBase_ interface ranther than _Source_? Coz I found that **fake_connnector** implements  _SimpleSourceBase_ interface.
2. CSV format is schema-less. Do I need to load additional json to ensure schma?

**Comment by garyli1019** [comment]
Hello @Jake-00 
1. `SimpleSourceBase` is a single parallelism source, but if we want to run it in multi parallelism, we need to implement a complete `Source` interface. The scenario we need multi parallelism would be reading multiple csv file under a path, or a big csv file we need to split(not sure if this is possible for csv). If you would like to support a single parallelism first and extend to multi parallelism in a future task. That's total ok as well. That's up to you :)
2. The way we handle the schema could be flexible. Some cases we may use the first line as schema, sometime the file doesn't have the schema or the schema is out of order. We could implement the standard way first(like other connector, include the schema in the configuration file) and support other ways later.

**Comment by Jake-00** [comment]
Hi @garyli1019 
Following your analysis, I have decided to implement single parallelism local csv source on standard way. And it comes two things needing discussion:
1. Referring to [csv-format](https://nightlies.apache.org/flink/flink-docs-master/docs/connectors/table/formats/csv/#csv-format) in Flink's docs, here is the demo conf below. How about this design？
```json
{  
  "job": {  
    "common": {  
      "job_id": -255,  
      "instance_id": -2035,  
      "job_name": "bitsail_local_csv_to_print_test",  
      "user_name": "test"  
    },  
    "reader": {  
      "class": "com.bytedance.bitsail.connector.local.csv.source.LocalCsvSource",  
      "file_path": "src/test/resources/student.csv",  
      "field_delimiter": ",",
      "disable-quote-character": true,
      "quote-character": "",
      "allow_comments": false,
      "ignore_parse_errors": false,
      "null_literal": "",
      "write_bigdecimal_in_scientific_notation": true,
      "columns": [  
        {  
          "name": "id",  
          "type": "long"  
        },  
        {  
          "name": "name",  
          "type": "string"  
        }  
      ]  
    },  
    "writer": {  
      "class": "com.bytedance.bitsail.connector.legacy.print.sink.PrintSink",  
      "writer_parallelism_num": 2  
    }  
  }  
}
```
2. Parsing a csv file to POJO objects by Jackson is convenient, but it may be difficult to parse each row of csv file to Row(defined in BitSail) object. So I try to import univocity-parsers to deal with row parsing problem. I am not sure whether using univocity-parsers is a right action for effective parsing.

**Comment by garyli1019** [comment]
hi @Jake-00 , sorry for the late. Regarding csv and json format, we already have it in the `bitsail-components/bitsail-component-format`, we could reuse the existing one.

**Comment by Jake-00** [comment]
The existing csv format tool really helps, and I create a pr: )
