### ISSUE TITLE
[BitSail][Runtime] Support latest JDK (11+)

### ISSUE THREAD

**Issue by lichang-bd** [bytedance/bitsail#118]
## Is your feature request related to a problem? Please describe

A clear and concise description of what the problem is. 

Example: I'm always frustrated when [...]

**Comment by lichang-bd** [comment]
#71

**Comment by garyli1019** [comment]
https://github.com/sofastack/sofa-ark/pull/521 found another project did the similar changes, we need to support different class loader method to support jdk 11

**Comment by love-star** [comment]
Get it!

**Comment by lichang-bd** [comment]
Due to compatibility issues, there are no plans to support Java 11 in the short term
