### ISSUE TITLE
[BitSail][Doc] Add BitSail Logo to the introduction section in ReadMe

### ISSUE THREAD

**Issue by lichang-bd** [bytedance/bitsail#125]
## Is your feature request related to a problem? Please describe

A clear and concise description of what the problem is. 

Example: I'm always frustrated when [...]

**Comment by lichang-bd** [comment]
<img width="144" alt="BitSaillogo" src="https://user-images.githubusercontent.com/69448640/200638310-84b0b84c-364c-4411-84f1-ea813543a827.png">

**Comment by garyli1019** [comment]
fixed by #152
