### ISSUE TITLE
[BitSail][Connector] Migrate larksheet legacy connector to V1 interface

### ISSUE THREAD

**Issue by lichang-bd** [bytedance/bitsail#134]
## Is your feature request related to a problem? Please describe

A clear and concise description of what the problem is. 

Example: I'm always frustrated when [...]

**Comment by liuxiaocs7** [comment]
@BlockLiu, @garyli1019 May I ask how to apply for developer permission? I applied on Feishu but got no feedback.

![image](https://user-images.githubusercontent.com/42756849/212834644-e06736d3-c899-4387-ba23-16e08ff162ca.png)

**Comment by garyli1019** [comment]
Not quite sure about this. Hi @ayonel , do you have any idea?
