### ISSUE TITLE
[BitSail][Connector] Migrate rocketmq Sink connector to V1 interface

### ISSUE THREAD

**Issue by lichang-bd** [bytedance/bitsail#137]
## Is your feature request related to a problem? Please describe

RMQ Source was completed, we need to migrate sink to V1 interface as well.

**Comment by lichang-bd** [comment]
already done

**Comment by beyond-up** [comment]
please assign to me, thx!

**Comment by beyond-up** [comment]
@garyli1019 @lichang-bd  
I submitted a PR for this issue, please help me review the code,thx!

**Comment by beyond-up** [comment]
I hava finished my pr, please help me review the code,thx!   @garyli1019 @lichang-bd @liuxiaocs7
