### ISSUE TITLE
[BitSail][Connector] Support INSERT IGNORE INTO in mysql connector.

### ISSUE THREAD

**Issue by BlockLiu** [bytedance/bitsail#142]
## Is your feature request related to a problem? Please describe

Current mysql writer in `bitsail-connector-jdbc` module supports the following two way to update data:

 - `INSERT INTO ...`
 - `INSERT INTO ... xxxx=VALUES(...) ON DUPLICATE KEY UPDATE`

This issue wants to support `INSERT IGORE INTO ...` in mysql connector.

## Additional context

N/A

**Comment by john8628** [comment]
please assign to me; i will try it ,thanks

**Comment by garyli1019** [comment]
@john8628 assigned to you, thanks!

**Comment by BlockLiu** [comment]
Hi @john8628, thanks for your contribution to the BitSail community. Would you like to join contributor chat group? Here is the QR code. If it expires, you can leave a message here. Look forward to your coming!
<img width="293" alt="ContributorGroup" src="https://user-images.githubusercontent.com/22468412/209900056-0bb69090-cdcd-4020-b57b-32309194474e.png">

**Comment by john8628** [comment]
expired, could you add me again; wechat zww8628

**Comment by yucongcong654** [comment]
我加您了 @john8628
