### ISSUE TITLE
[BitSail][Connector] Redis writer supports HMSET command.

### ISSUE THREAD

**Issue by BlockLiu** [bytedance/bitsail#144]
## Is your feature request related to a problem? Please describe

Current Redis writer supports HSET command.

In some cases, an upstream row may contain one key and multiple <key-value> pairs, which is not supported now.
So this issue wants to support HMSET in redis writer.

**Comment by liugddx** [comment]
assign to me,thanks

**Comment by garyli1019** [comment]
@liugddx assigned to you!

**Comment by garyli1019** [comment]
@liugddx hello, just checking how's everything going with this issue. We have a contributor group to discuss dev issue. Please feel free to join if you are interested
![img_v2_0cd2da0d-3975-4a0e-b257-6ee8a1223c3g](https://user-images.githubusercontent.com/23007841/204690399-b0063fc4-09e9-4e95-a0f0-f07eefe245fb.jpg)
