### ISSUE TITLE
[BitSail][Connector] Support more send method in Kafka writer.

### ISSUE THREAD

**Issue by BlockLiu** [bytedance/bitsail#147]
## Is your feature request related to a problem? Please describe

Current `KafkaOutputFormat` supports only the following two send method in KafkaProducer:
 - `public Future<RecordMetadata> send(ProducerRecord<K, V> record, Callback callback)`
 - `public Future<RecordMetadata> send(ProducerRecord<K, V> record, Callback callback)`

Sometimes, one may want to add more data in the ProducerRecord such as key or header.
So this issue wants to extend current KafkaOutputFormat to support more send method.

**Comment by zeliu** [comment]
hi @BlockLiu  I'd like to have a try, please assign it to me.

**Comment by BlockLiu** [comment]
Sure, take your time!
