### ISSUE TITLE
目前Bitsail 文档没有网站在线阅读是吗, 后期是否会加上文档网站呢。

### ISSUE THREAD

**Issue by aozeyu** [bytedance/bitsail#156]
## Is your feature request related to a problem? Please describe

A clear and concise description of what the problem is. 

Example: I'm always frustrated when [...]

**Comment by yucongcong654** [comment]
是不是可以社区激励形式来共建开发？

**Comment by aozeyu** [comment]
加一

**Comment by BlockLiu** [comment]
目前有正在支持文档网站建设，辛苦先在doc目录进行文档查找。

**Comment by aozeyu** [comment]
@BlockLiu 好的感谢你的回复

**Comment by BlockLiu** [comment]
也鼓励大家完善或者补齐bitsail connector或者功能模块文档介绍哈
