### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by wuchunfu** [bytedance/bitsail#158]
When I start in the local mode, an error is reported. How can I solve it? The following is the error message

```bash
2022-11-09 23:56:57,627 ERROR entry.Entry: Exception occurred when run command .
java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at com.bytedance.bitsail.client.entry.Entry.<init>(Entry.java:71)
        at com.bytedance.bitsail.client.entry.Entry.main(Entry.java:86)
```

**Comment by garyli1019** [comment]
Hi @wuchunfu , which JDK version are you using?

**Comment by wuchunfu** [comment]
> Hi @wuchunfu , which JDK version are you using?

1.8.0_202

**Comment by garyli1019** [comment]
found a related issue https://github.com/microsoft/azure-maven-plugins/issues/988 , I believe that's related to jdk. I will take a look later today

**Comment by Jake-00** [comment]
I have met with same error when using openjdk version "11.0.17"

**Comment by lichang-bd** [comment]
Yes, currently jdk11 is not supported, only jdk8
