### ISSUE TITLE
About download dependencies with maven?

### ISSUE THREAD

**Issue by aozeyu** [bytedance/bitsail#159]
Big guy, why can't the maven download dependencies be downloaded after I fork the bitsail repository? There is no problem with my maven configuration, and other projects can download dependencies.

<img width="1266" alt="截屏2022-11-10 09 41 49" src="https://user-images.githubusercontent.com/55688386/200979692-6c53fc36-2439-4546-8e87-d208e72e3be6.png">
<img width="732" alt="截屏2022-11-10 09 42 09" src="https://user-images.githubusercontent.com/55688386/200979729-d5d54716-6379-458e-88dd-e51ccbea9f06.png">
The url of Alibaba Cloud is configured in my settings.xml

**Comment by aozeyu** [comment]
@microxxx 
@onebird 
@snakev

**Comment by aozeyu** [comment]
I tried to google but the solution told me that there is a problem with maven configuration, but I checked my maven configuration and there is no problem, please help me solve my confusion?

**Comment by aozeyu** [comment]
The download dependency has been stuck in the download plugin

**Comment by garyli1019** [comment]
@aozeyu Hi, looks like this is a downloading issue. Instead of downloading it through IDEA, you can also try run the `build.sh` script and download the dependency through the maven command line, in this case you will see which package was stuck.

**Comment by aozeyu** [comment]
@garyli1019  Thank you for your answer, I tried to use sh ./build.sh to download, the current situation is that I can download most of the dependencies, but when I download a plugin, I get an error, it seems to be something under bitsail-all?

<img width="1280" alt="截屏2022-11-10 11 08 58" src="https://user-images.githubusercontent.com/55688386/200991868-a9daef5b-2d89-44dc-a947-2dcf939e91f4.png">
<img width="1273" alt="截屏2022-11-10 11 12 05" src="https://user-images.githubusercontent.com/55688386/200991943-c6fa5ad4-4c8a-4503-bc2f-d49a426a046a.png">

**Comment by aozeyu** [comment]
Do these plug-ins have any impact on the whole? If so, how can I download them all? Please answer my confusion?
@garyli1019

**Comment by garyli1019** [comment]
@aozeyu Would you try to remove `org.apache.common` package under the maven cache `~/.m2/repository` and try remove related package as well? It is possible the cached packages were corrupted.

**Comment by aozeyu** [comment]
@garyli1019  

I deleted my local repository ~/.m2/repository, re-executed the sh ./build.sh command to download most of the packages, but still can't download plugins, I tried google, Google told me that it may not be the maven problem is the plugin the problem 😂 
<img width="1280" alt="截屏2022-11-10 14 33 32" src="https://user-images.githubusercontent.com/55688386/201020055-0cb0af3f-cdcc-4d0f-a334-2490f8ac84a8.png">
<img width="1232" alt="截屏2022-11-10 14 33 07" src="https://user-images.githubusercontent.com/55688386/201020068-7e2823ef-1fde-40bf-b66a-d9d04a0ff91f.png">

**Comment by aozeyu** [comment]
Is it caused by some plugins installed in my local idea 😂 @garyli1019

**Comment by garyli1019** [comment]
@aozeyu what is your JDK version?

**Comment by aozeyu** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    我的jdk版本是1.8,是必须要17以上吗
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                3484766443
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
 
    

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            Gary ***@***.***>
            
        
      
      
        
         Date 
        
        
        11/10/2022 14:53
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [bytedance/bitsail] About download dependencies with maven? (Issue #159)
        
      
    
  
  
@aozeyu what is your JDK version?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by love-star** [comment]
you can use "mvn -v" to see what java version your maven use. if it is oracle jdk 8, try click your idea File->Invalidate Caches and reload maven.

**Comment by love-star** [comment]
@aozeyu you can use "mvn -v" to see what java version your maven use. if it is oracle jdk 8, try click your idea File->Invalidate Caches and reload maven.

**Comment by aozeyu** [comment]
@love-star Thank you for your help, the advice you gave is very helpful for me, I solved the problem and successfully downloaded the dependencies, thank you for your reply.
<img width="1245" alt="截屏2022-11-10 19 50 30" src="https://user-images.githubusercontent.com/55688386/201083398-8c6a0cf6-5b1f-48e0-92cb-29638d398e60.png">

**Comment by love-star** [comment]
@aozeyu You're welcome, We're glad you're interested in Bitsail. I hope this project can help you, and look forward to your Pull Requests!
