### ISSUE TITLE
About whether it is possible to annotate enum values？

### ISSUE THREAD

**Issue by aozeyu** [bytedance/bitsail#162]
Is this necessary? Is it more friendly to add comments to enumeration fields for future maintainers?
Because people like me who are new to this project may want to understand the function of this enumeration value, do I need to add a comment? If it is not necessary, just pretend I didn't say it.  😂
<img width="1263" alt="截屏2022-11-10 22 26 07" src="https://user-images.githubusercontent.com/55688386/201117898-93387e69-575e-4c21-a2f0-b9c2e1728959.png">

**Comment by love-star** [comment]
@aozeyu Of course you can, just do it and make your PRs, remember to use english and the code check-style when you add comments.

**Comment by aozeyu** [comment]
@love-star Ok, thanks for your reply, I thought I could add it 😂.

**Comment by love-star** [comment]
@garyli1019 perhaps this issue can be closed?
