### ISSUE TITLE
Bitsail support collection of data synchronization table, field lineage information

### ISSUE THREAD

**Issue by FantasticLiar** [bytedance/bitsail#175]
## Is your feature request related to a problem? Please describe
Noop

## Describe the solution you'd like

I want to be able to easily collect the metadata information and blood relationship information of the task after the task is completed, so as to facilitate the development of subsequent data governance work

## Describe alternatives you've considered

Is there some message bus that can easily collect metadata and bloodline information?

## Additional context

Noop

**Comment by lichang-bd** [comment]
This question is very good, but this is the capability provided by the data development platform or metadata platform, and the positioning of data integration is for data synchronization.
