### ISSUE TITLE
About release

### ISSUE THREAD

**Issue by StareStarrySky** [bytedance/bitsail#194]
## Is your feature request related to a problem? Please describe

A clear and concise description of what the problem is. 

Example: I'm always frustrated when [...]

- I don't know which version or branch or commit can be used to production environment.

## Describe the solution you'd like

- Add a tag or pre-release or something can tell this is a milepost.

## Describe alternatives you've considered

- Write something like this in [README.md](https://github.com/bytedance/bitsail/blob/master/README.md): You can use the first commit in master as the newest version at present.

**Comment by garyli1019** [comment]
Hi, we are preparing the first release. Thanks for you suggestion and we will update the README. For now you could use the latest commit on master branch.
