### ISSUE TITLE
Add DelegateFlinkWriter support on Druid sink connector

### ISSUE THREAD

**Issue by ysamchu** [bytedance/bitsail#195]
## Is your feature request related to a problem? Please describe

This is a follow-up feature on Druid sink connector support. Refer to [comment](https://github.com/bytedance/bitsail/pull/187#discussion_r1027919957) in Druid support PR, DelegateFlinkWriter is necessary to avoid OOM in practice.

## Describe the solution you'd like

Add DelegateFlinkWriter to Druid sink connector.

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by lichang-bd** [comment]
already supported
