### ISSUE TITLE
0.1.0 Release Discussion

### ISSUE THREAD

**Issue by garyli1019** [bytedance/bitsail#197]
Hello, I will be the release manager for the 0.1.0 Release. All the release related discussion will be on this issue. I will also use this issue to track all the blocker issues. Thanks

**Comment by lichang-bd** [comment]
good job，when is 0.1.0 expected to be released

**Comment by garyli1019** [comment]
https://github.com/bytedance/bitsail/releases/tag/release-0.1.0 0.1.0 released
