### ISSUE TITLE
windows  下无法使用

### ISSUE THREAD

**Issue by slyang520** [bytedance/bitsail#203]

**Comment by QiLuo-BD** [comment]
could you add more details, like your Windows & other dependency versions,
and detail error messages?

**Comment by slyang520** [comment]
![image](https://user-images.githubusercontent.com/8638524/203601914-b9b0d93d-1ea2-478b-80e6-45255a049251.png)

![image](https://user-images.githubusercontent.com/8638524/203601760-cd561c5e-c73d-42f4-8333-e01d9b409a68.png)

**Comment by QiLuo-BD** [comment]
@garyli1019 could you help look into this issue? seems like a port issue

**Comment by garyli1019** [comment]
Not sure if we can run the integration test on Windows. I will try in my windows machine to see if I can reproduce.

**Comment by lichang-bd** [comment]
Has this problem been solved @slyang520 @garyli1019 ? If not , maybe we can have a test in windows environment @BlockLiu

**Comment by slyang520** [comment]
> Has this problem been solved @slyang520 @garyli1019 ? If not , maybe we can have a test in windows environment @BlockLiu

还用不了

**Comment by lichang-bd** [comment]
please have a look about this issue @garyli1019

**Comment by garyli1019** [comment]
hello @slyang520 , we found out some unit tests and integration test failed to run on Windows, due to Flink or the TestContainer project we rely on. Unforunately, we are not able to fix those issue, so now we only support compile on Windows and run tests on Macos and Linux.
