### ISSUE TITLE
build error org.apache.hadoop.io not exits

### ISSUE THREAD

**Issue by yongster** [bytedance/bitsail#219]
##  build error  程序包org.apache.hadoop.io不存在

in  bitsail-flink-row-parser model 

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project bitsail-flink-row-parser: Compilation failure: Compilation failure:
[ERROR] /opt/sourceCode/bitsail-master/bitsail-components/bitsail-flink-row-parser/src/main/java/com/bytedance/bitsail/batch/parser/row/HiveRowBuilder.java:[43,28] 程序包org.apache.hadoop.io不存在
[ERROR] /opt/sourceCode/bitsail-master/bitsail-components/bitsail-flink-row-parser/src/main/java/com/bytedance/bitsail/batch/parser/row/HiveRowBuilder.java:[44,28] 程序包org.apache.hadoop.io不存在
[ERROR] /opt/sourceCode/bitsail-master/bitsail-components/bitsail-flink-row-parser/src/main/java/com/bytedance/bitsail/batch/parser/row/HiveRowBuilder.java:[45,28] 程序包org.apache.hadoop.io不存在
[ERROR] /opt/sourceCode/bitsail-master/bitsail-components/bitsail-flink-row-parser/src/main/java/com/bytedance/bitsail/batch/parser/row/HiveRowBuilder.java:[46,28] 程序包org.apache.hadoop.io不存在
[ERROR] /opt/sourceCode/bitsail-master/bitsail-components/bitsail-flink-row-parser/src/main/java/com/bytedance/bitsail/batch/parser/row/HiveRowBuilder.java:[47,28] 程序包org.apache.hadoop.io不存在
[ERROR] /opt/sourceCode/bitsail-master/bitsail-components/bitsail-flink-row-parser/src/main/java/com/bytedance/bitsail/batch/parser/row/HiveRowBuilder.java:[48,28] 程序包org.apache.hadoop.io不存在
[ERROR] /opt/sourceCode/bitsail-master/bitsail-components/bitsail-flink-row-parser/src/main/java/com/bytedance/bitsail/batch/parser/row/HiveRowBuilder.java:[49,28] 程序包org.apache.hadoop.io不存在
[ERROR] /opt/sourceCode/bitsail-master/bitsail-components/bitsail-flink-row-parser/src/main/java/com/bytedance/bitsail/batch/parser/row/HiveRowBuilder.java:[89,66] 找不到符号
[ERROR]   符号:   类 Writable
[ERROR]   位置: 类 com.bytedance.bitsail.batch.parser.row.HiveRowBuilder
[ERROR] /opt/sourceCode/bitsail-master/bitsail-components/bitsail-flink-row-parser/src/main/java/com/bytedance/bitsail/batch/parser/row/HiveRowBuilder.java:[102,71] 找不到符号
[ERROR]   符号:   类 Writable
[ERROR]   位置: 类 com.bytedance.bitsail.batch.parser.row.HiveRowBuilder
[ERROR] /opt/sourceCode/bitsail-master/bitsail-components/bitsail-flink-row-parser/src/main/java/com/bytedance/bitsail/batch/parser/row/HiveRowBuilder.java:[122,75] 找不到符号
[ERROR]   符号:   类 Writable
[ERROR]   位置: 类 com.bytedance.bitsail.batch.parser.row.HiveRowBuilder
[ERROR] /opt/sourceCode/bitsail-master/bitsail-components/bitsail-flink-row-parser/src/main/java/com/bytedance/bitsail/batch/parser/row/HiveRowBuilder.java:[138,81] 找不到符号
[ERROR]   符号:   类 Writable
[ERROR]   位置: 类 com.bytedance.bitsail.batch.parser.row.HiveRowBuilder
[ERROR] /opt/sourceCode/bitsail-master/bitsail-components/bitsail-flink-row-parser/src/main/java/com/bytedance/bitsail/batch/parser/row/HiveRowBuilder.java:[156,44] 找不到符号
[ERROR]   符号:   类 ArrayWritable
[ERROR]   位置: 类 com.bytedance.bitsail.batch.parser.row.HiveRowBuilder
[ERROR] /opt/sourceCode/bitsail-master/bitsail-components/bitsail-flink-row-parser/src/main/java/com/bytedance/bitsail/batch/parser/row/HiveRowBuilder.java:[156,13] 找不到符号
[ERROR]   符号:   类 ArrayWritable
[ERROR]   位置: 类 com.bytedance.bitsail.batch.parser.row.HiveRowBuilder
[ERROR] /opt/sourceCode/bitsail-master/bitsail-components/bitsail-flink-row-parser/src/main/java/com/bytedance/bitsail/batch/parser/row/HiveRowBuilder.java:[165,48] 找不到符号
[ERROR]   符号:   类 Writable
[ERROR]   位置: 类 com.bytedance.bitsail.batch.parser.row.HiveRowBuilder
[ERROR] /opt/sourceCode/bitsail-master/bitsail-components/bitsail-flink-row-parser/src/main/java/com/bytedance/bitsail/batch/parser/row/HiveRowBuilder.java:[177,52] 找不到符号
[ERROR]   符号:   类 Writable
[ERROR]   位置: 类 com.bytedance.bitsail.batch.parser.row.HiveRowBuilder
[ERROR] /opt/sourceCode/bitsail-master/bitsail-components/bitsail-flink-row-parser/src/main/java/com/bytedance/bitsail/batch/file/parser/PbBytesParser.java:[39,28] 程序包org.apache.hadoop.io不存在
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :bitsail-flink-row-parser

**Comment by lichang-bd** [comment]
already solved
