### ISSUE TITLE
[BitSail][Feature] Support set JedisPoolConfig in RedisSink.

### ISSUE THREAD

**Issue by BlockLiu** [bytedance/bitsail#254]
## Is your feature request related to a problem? Please describe

Current RedisSink uses fixed JedisPoolConfig, like max total connection number, max idle connection number, min idle connection number and others.

## Describe the solution you'd like

Maybe we can add config options to support set JedisPoolConfig.

**Comment by liuxiaocs7** [comment]
These settings seems already exists in connector-redis-V1 user defined configuration, code is here: https://github.com/bytedance/bitsail/blob/fbc5d22e1901f86a54cd388967629541a1a51739/bitsail-connectors/connector-redis/src/main/java/com/bytedance/bitsail/connector/redis/option/RedisWriterOptions.java#L94-L113

this issue means to improve connector-redis-legacy?

**Comment by BlockLiu** [comment]
Yeah, it meanse connector-redis-legacy, because connector-redis was merged after this issue.
But now that the new connector-redis has supported such options, I think this issue can be skipped.

**Comment by BlockLiu** [comment]
Many thanks for your support and comment.
