### ISSUE TITLE
[BitSail][UT] Add ut for DorisRowConverter.

### ISSUE THREAD

**Issue by BlockLiu** [bytedance/bitsail#256]
##  Please describe the features.

We want add more unit test for DorisRowConverter.

**Comment by HendSame** [comment]
![image](https://user-images.githubusercontent.com/9264192/209297122-6206e0df-c940-4ee5-80b1-4a030e33f4bf.png)
Missing dependencies！

**Comment by HendSame** [comment]
Maybe it can run unit tests well, before merging code.

**Comment by manymango** [comment]
Hi, i want to try it, please assign to me.

**Comment by yucongcong654** [comment]
Hi manymango, thanks for your contribution to the BitSail community. we build a group for all contributor.Here is the QR code. If it expires, you can add WeChat ID 13651994967. Look forward to your arrival! @manymango 
![1201675133901_ pic](https://user-images.githubusercontent.com/87509126/215684414-38657c21-2b11-450b-9fa4-4fef364039d6.jpg)
