### ISSUE TITLE
The config plugin name com.bytedance.bitsail.connector.legacy.hive.source.HiveInputFormat is not found

### ISSUE THREAD

**Issue by zhouqingfa** [bytedance/bitsail#277]
1.The exceptions are as follows:
The cause of the job failure maybe due to:
java.lang.RuntimeException: com.bytedance.bitsail.common.BitSailException: Code:[Common-00], Describe:[The configuration file which you supplied is not correct, please check
.] - The config plugin name com.bytedance.bitsail.connector.legacy.hive.source.HiveInputFormat is not found!

2.hive to print json conf:
{
  "job": {
    "common": {
      "job_id": 312,
      "instance_id": 3124,
      "job_name": "BitSail_fake_to_print_test",
      "user_name": "xxx"
    },
    "writer": {
      "class": "com.bytedance.bitsail.connector.legacy.print.sink.PrintSink"
    },
    "reader": {
      "class": "com.bytedance.bitsail.connector.legacy.hive.source.HiveInputFormat",
      "columns": [
        {
          "index": 0,
          "name": "pv",
          "type": "string"
        },
        {
          "index": 1,
          "name": "uv",
          "type": "string"
        },
        {
          "index": 2,
          "name": "dt",
          "type": "string"
        }
      ],
      "db_name": "default",
      "table_name": "dwd_test_phy_v1_di",
      "metastore_properties": "{\"hive.metastore.uris\":\"xxx\"}",
      "partition": "dt=20221221",
      "parallelism_num": 2,
      "source_engine": "hive"
    }
  }
}

3.The directory structure is as follows:
![Jietu20221223-150021](https://user-images.githubusercontent.com/121280838/209288005-a6c66f5a-433f-4f74-90e3-cadbeabc9ed8.png)

**Comment by zhouqingfa** [comment]
> @zhouqingfa Can you see the dir which name mapping below the connectors?

No such directory , Compile the source code several times without mapping directory , This command was used : mvn clean package -pl bitsail-dist -am -Dmaven.test.skip=true

**Comment by lichang-bd** [comment]
maybe you can use the build.sh in the repo directly and try again @zhouqingfa
