### ISSUE TITLE
[BitSail][LICENSE] update Copyright time to 2022-2023 in LICENSE Header File and Website

### ISSUE THREAD

**Issue by lichang-bd** [bytedance/bitsail#351]
## Is your feature request related to a problem? Please describe

A clear and concise description of what the problem is. 

Example: I'm always frustrated when [...]

## Additional context
Copyright 2022-2023 Bytedance Ltd. and/or its affiliates.

**Comment by wuchunfu** [comment]
@lichang-bd I will finish it, please assign it to me
