### ISSUE TITLE
[BitSail][Website] update copyright time from 2018-2022 to 2022-2023

### ISSUE THREAD

**Issue by lichang-bd** [bytedance/bitsail#359]
https://bytedance.github.io/bitsail/, at the bottom of home page

Before Change :
Apache LICENSE 2.0 Licensed, Copyright 2018-2022 BitSail All Rights Reserved

After Change:
Apache LICENSE 2.0 Licensed, Copyright 2022-2023 BitSail All Rights Reserved

**Comment by garyli1019** [comment]
closed by #361
