### ISSUE TITLE
[BitSail][Doc] BitSail homepage is is down

### ISSUE THREAD

**Issue by love-star** [bytedance/bitsail#375]
## Describe the bug
BitSail homepage is is down.

## To Reproduce
![image](https://user-images.githubusercontent.com/47937942/217705717-3b98011e-e53e-4041-93e5-6e09a14bc621.png)

I have read the history of github page deployment.(https://github.com/bytedance/bitsail/actions/runs/4121927501/jobs/7118110589)
It looks comes a problem like that:
```json
{"$id":"1","innerException":null,"message":"The user 'System:PublicAccess;aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa' is not authorized to access this resource.","typeName":"Microsoft.TeamFoundation.Framework.Server.UnauthorizedRequestException, Microsoft.TeamFoundation.Framework.Server","typeKey":"UnauthorizedRequestException","errorCode":0,"eventId":3000}
```
Is it an auth problem?

**Comment by lichang-bd** [comment]
@john8628 please have a look

**Comment by lichang-bd** [comment]
solved
