### ISSUE TITLE
[BitSail][Feature] Optimize type system error message

### ISSUE THREAD

**Issue by lichang-bd** [bytedance/bitsail#379]
## Is your feature request related to a problem? Please describe

At present, if the data source type is configured incorrectly, only a null pointer error will be reported, which is not convenient for problem location and troubleshooting

<img width="588" alt="image" src="https://user-images.githubusercontent.com/69448640/217778459-5879ee21-b363-494f-ba1f-d05f6af34636.png">

![image](https://user-images.githubusercontent.com/69448640/217778515-c8180036-d788-40c7-a66e-58502792bba3.png)

## Describe the solution you'd like
For types that cannot be recognized, errors need to be thrown in time

<img width="904" alt="image" src="https://user-images.githubusercontent.com/69448640/217778861-d39bacf8-d0c9-4d4c-822d-5f82f327f277.png">

**Comment by liumengkai** [comment]
assigne me please
@lichang-bd

**Comment by lichang-bd** [comment]
OK，look forward to your contribution. @liumengkai
