### ISSUE TITLE
[Improve][Doc] Add flow control parameters and instructions

### ISSUE THREAD

**Issue by lichang-bd** [bytedance/bitsail#398]
### Description

At present, the Common parameter has the description of the parallelism setting and dirty data setting, lacks the flow control parameter and description
<img width="1618" alt="image" src="https://user-images.githubusercontent.com/69448640/218916644-e56d423d-d9d5-438d-bdb9-a1113b2b2742.png">

we need to add  the description of the flow control in the common setting
reader_transport_channel_speed_byte         控制单并发读的流量,  X字节/S
reader_transport_channel_speed_record     控制单并发读的速度，X条/S
writer_transport_channel_speed_byte          控制单并发写的流量,   Y字节/S
writer_transport_channel_speed_record       控制单并发写的速度,   Y条/S

### BitSail Component or Code Module

BitSail Doc

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Fnck** [comment]
Hi there, I would like to finish this task.

**Comment by lichang-bd** [comment]
great， look forward to your contribution @Fnck

**Comment by yucongcong654** [comment]
Hi Fnck, thanks for your contribution to the BitSail community. we build a group for all contributor.Here is the QR code. If it expires, you can add WeChat ID 13651994967. Look forward to your arrival! @Fnck 
![1331676963531_ pic](https://user-images.githubusercontent.com/87509126/220273721-3095815e-d831-4a5f-b481-71d40b176412.jpg)
