### ISSUE TITLE
[DOC] Change Download link to BitSail Release Page

### ISSUE THREAD

**Issue by lichang-bd** [bytedance/bitsail#410]
### Description

The download link on the bitsail homepage links to the github homepage, we need to change the link to the bitsail release page(https://github.com/bytedance/bitsail/releases)

<img width="1675" alt="image" src="https://user-images.githubusercontent.com/69448640/220265340-86d430b4-90f6-496f-a387-066898f18180.png">

### BitSail Component or Code Module

BitSail Doc

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ciertou** [comment]
https://github.com/bytedance/bitsail/issues/410 
handle it.

**Comment by yucongcong654** [comment]
Hi ciertou, thanks for your contribution to the BitSail community. we build a group for all contributor.Here is the QR code. If it expires, you can add WeChat ID 13651994967. Look forward to your arrival! @ciertou 
![1331676963531_ pic](https://user-images.githubusercontent.com/87509126/220865112-798e2c25-42dd-4e36-b10b-d9b8a9e24b6d.jpg)

**Comment by lichang-bd** [comment]
> #410 handle it.

great job，thanks to you contribution, we also have many other issues，take your time @ciertou
