### ISSUE TITLE
flink版本有支持1.13吗

### ISSUE THREAD

**Issue by zengqinchris** [bytedance/bitsail#58]
## Is your feature request related to a problem? Please describe

A clear and concise description of what the problem is. 

Example: I'm always frustrated when [...]

**Comment by garyli1019** [comment]
当前只支持flink 1.11，roadmap中有支持多版本flink

**Comment by sjq1992** [comment]
多版本的支持是在flink基础api不变的情况下向下兼容的么，即bitsail一个版本能运行在flink 1.11-1.14多个版本上？

**Comment by garyli1019** [comment]
@sjq1992 计划是这样的，flink接口不兼容的情况加基于不同的版本编译

**Comment by garyli1019** [comment]
issue created #108
