### ISSUE TITLE
found some types in readme

### ISSUE THREAD

**Issue by EMsnap** [bytedance/bitsail#62]
## Describe the bug

see below 

## To Reproduce

![image](https://user-images.githubusercontent.com/26538404/198211158-8190eb80-006b-49a5-badb-e7c8d28a594b.png)

## Screenshots

![image](https://user-images.githubusercontent.com/26538404/198211158-8190eb80-006b-49a5-badb-e7c8d28a594b.png)

**Comment by lichang-bd** [comment]
@EMsnap 
Thanks for the correction, it's being fixed right now
